In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [1]:
import pandas as pd

file_path = "/kaggle/input/datasets/razanihababdellatif/womens-e-commerce-clothing-reviews-and-sales/women_clothing_50k.csv"

df = pd.read_csv(file_path)

df.head()

,product_id,category,subcategory,material,color,size,season,style,price_usd,discount_percent,rating,review_count,stock_quantity,units_sold,return_rate
0,WC000001,Jeans,Skinny Jeans,Denim,Red,M,Summer,Business Casual,37.00,0,0.0,0,2,14,0.17
1,WC000002,Dresses,Wrap Dress,Cotton,White,M,Winter,Casual,59.12,10,0.0,0,13,31,0.13
2,WC000003,T-Shirts,V-Neck T-Shirt,Cotton,Purple,M,All Season,Casual,27.65,0,0.0,0,10,2,0.11
3,WC000004,Sweaters,Oversized Sweater,Wool,Brown,S,Winter,Formal,72.64,0,2.9,17,104,292,0.14
4,WC000005,Sweaters,Oversized Sweater,Wool,White,M,Winter,Minimalist,72.61,40,0.0,0,12,15,0.07

In [2]:
df.columns.tolist()

['product_id',
 'category',
 'subcategory',
 'material',
 'color',
 'size',
 'season',
 'style',
 'price_usd',
 'discount_percent',
 'rating',
 'review_count',
 'stock_quantity',
 'units_sold',
 'return_rate']

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_id        50000 non-null  object
 1   category          50000 non-null  object
 2   subcategory       50000 non-null  object
 3   material          50000 non-null  object
 4   color             50000 non-null  object
 5   size              50000 non-null  object
 6   season            50000 non-null  object
 7   style             50000 non-null  object
 8   price_usd         50000 non-null  float64
 9   discount_percent  50000 non-null  int64
 10  rating            50000 non-null  float64
 11  review_count      50000 non-null  int64
 12  stock_quantity    50000 non-null  int64
 13  units_sold        50000 non-null  int64
 14  return_rate       50000 non-null  float64
dtypes: float64(3), int64(4), object(8)
memory usage: 5.7+ MB

In [13]:
features = [
    'category',
    'subcategory',
    'material',
    'color',
    'season',
    'style'
]

df['combined_features'] = (
    df['category'] + ' ' +
    df['category'] + ' ' +
    df['subcategory'] + ' ' +
    df['subcategory'] + ' ' +
    df['subcategory'] + ' ' +
    df['material'] + ' ' +
    df['color'] + ' ' +
    df['season'] + ' ' +
    df['style']
)
df[['product_id', 'combined_features']].head()

  product_id                                  combined_features
0   WC000001  Jeans Jeans Skinny Jeans Skinny Jeans Skinny J...
1   WC000002  Dresses Dresses Wrap Dress Wrap Dress Wrap Dre...
2   WC000003  T-Shirts T-Shirts V-Neck T-Shirt V-Neck T-Shir...
3   WC000004  Sweaters Sweaters Oversized Sweater Oversized ...
4   WC000005  Sweaters Sweaters Oversized Sweater Oversized ...

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

feature_matrix = vectorizer.fit_transform(
    df['combined_features']
)

print(feature_matrix.shape)

(50000, 108)

In [17]:
from sklearn.neighbors import NearestNeighbors

In [18]:
model = NearestNeighbors(
    metric='cosine',
    algorithm='brute',
    n_neighbors=6
)

model.fit(feature_matrix)

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=6)

In [19]:
def recommend(product_id, n_recommendations=5):

    # Trouver l'index du produit
    matches = df.index[df['product_id'] == product_id]

    if len(matches) == 0:
        print("Produit non trouvé.")
        return None

    product_index = matches[0]

    # Trouver les voisins les plus proches
    distances, indices = model.kneighbors(
        feature_matrix[product_index],
        n_neighbors=n_recommendations + 1
    )

    recommended_indices = indices.flatten()[1:]
    recommended_distances = distances.flatten()[1:]

    # Résultat
    recommendations = df.iloc[recommended_indices][[
        'product_id',
        'category',
        'subcategory',
        'material',
        'color',
        'season',
        'style',
        'size',
        'price_usd',
        'rating',
        'return_rate'
    ]].copy()

    recommendations['similarity_score'] = 1 - recommended_distances

    return recommendations

In [20]:
df[['product_id', 'category', 'subcategory']].head(10)

  product_id   category        subcategory
0   WC000001      Jeans       Skinny Jeans
1   WC000002    Dresses         Wrap Dress
2   WC000003   T-Shirts     V-Neck T-Shirt
3   WC000004   Sweaters  Oversized Sweater
4   WC000005   Sweaters  Oversized Sweater
5   WC000006    Dresses         Mini Dress
6   WC000007    Blouses   Button-Up Blouse
7   WC000008    Dresses        Shirt Dress
8   WC000009  Jumpsuits   Utility Jumpsuit
9   WC000010    Dresses        Shirt Dress

In [21]:
recommend('PROD_00001')

Produit non trouvé.

In [25]:
recommend("WC000001")

,product_id,category,subcategory,material,color,season,style,size,price_usd,rating,return_rate,similarity_score
44628,WC044629,Jeans,Skinny Jeans,Denim,Red,Summer,Business Casual,M,98.46,4.7,0.13,1.000000
33318,WC033319,Jeans,Skinny Jeans,Denim,Red,Summer,Casual,M,50.36,3.8,0.10,0.992399
41747,WC041748,Jeans,Skinny Jeans,Denim,Red,Summer,Casual,L,84.64,3.8,0.11,0.992399
20576,WC020577,Jeans,Skinny Jeans,Denim,Red,Autumn,Business Casual,XS,93.74,5.0,0.13,0.987888
11814,WC011815,Jeans,Skinny Jeans,Denim,Red,Winter,Business Casual,S,62.41,5.0,0.12,0.987716

In [27]:
df[df['product_id'] == "WC000001"]

,product_id,category,subcategory,material,color,size,season,style,price_usd,discount_percent,rating,review_count,stock_quantity,units_sold,return_rate,combined_features
0,WC000001,Jeans,Skinny Jeans,Denim,Red,M,Summer,Business Casual,37.0,0,0.0,0,2,14,0.17,Jeans Jeans Skinny Jeans Skinny Jeans Skinny J...

In [28]:
df.iloc[0]

product_id                                                    WC000001
category                                                         Jeans
subcategory                                               Skinny Jeans
material                                                         Denim
color                                                              Red
size                                                                 M
season                                                          Summer
style                                                  Business Casual
price_usd                                                         37.0
discount_percent                                                     0
rating                                                             0.0
review_count                                                         0
stock_quantity                                                       2
units_sold                                                          14
return_rate                                                       0.17
combined_features    Jeans Jeans Skinny Jeans Skinny Jeans Skinny J...
Name: 0, dtype: object

In [29]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.neighbors import NearestNeighbors

In [30]:
features = [
    'category',
    'subcategory',
    'material',
    'color',
    'season',
    'style'
]

encoder = OneHotEncoder(handle_unknown='ignore')

feature_matrix = encoder.fit_transform(df[features])

print(feature_matrix.shape)

(50000, 105)

In [31]:
model = NearestNeighbors(
    metric='cosine',
    algorithm='brute',
    n_neighbors=10
)

model.fit(feature_matrix)

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=10)

In [ ]:
def recommend(product_id, n_recommendations=5):

    # Trouver le produit
    matches = df.index[df['product_id'] == product_id]

    if len(matches) == 0:
        print("Produit non trouvé.")
        return None

    product_index = matches[0]

    # Trouver les voisins similaires
    distances, indices = model.kneighbors(
        feature_matrix[product_index],
        n_neighbors=n_recommendations + 1
    )

    recommended_indices = indices.flatten()[1:]
    recommended_distances = distances.flatten()[1:]

    recommendations = df.iloc[recommended_indices][[
        'product_id',
        'category',
        'subcategory',
        'material',
        'color',
        'size',
        'season',
        'style',
        'price_usd',
        'rating',
        'units_sold',
        'return_rate'
    ]].copy()

    recommendations['similarity_score'] = (
        1 - recommended_distances
    )

    return recommendations.sort_values(
        'similarity_score',
        ascending=False
    )

In [32]:
recommend("WC000001")

,product_id,category,subcategory,material,color,season,style,size,price_usd,rating,return_rate,similarity_score
44628,WC044629,Jeans,Skinny Jeans,Denim,Red,Summer,Business Casual,M,98.46,4.7,0.13,1.000000
35482,WC035483,Jeans,Skinny Jeans,Denim,Navy,Summer,Business Casual,L,85.86,3.1,0.21,0.833333
49946,WC049947,Jeans,Skinny Jeans,Denim,White,Summer,Business Casual,M,68.14,2.5,0.16,0.833333
35581,WC035582,Jeans,Skinny Jeans,Denim,Navy,Summer,Business Casual,M,73.97,0.0,0.00,0.833333
35208,WC035209,Jeans,Skinny Jeans,Denim,Red,Summer,Minimalist,M,94.01,0.0,0.15,0.833333

In [49]:
import numpy as np

def recommend_hybrid(product_id, n_recommendations=5):
    # Trouver le produit (position réelle dans df, pas le label)
    matches = np.flatnonzero(df['product_id'].values == product_id)
    if len(matches) == 0:
        print("Produit non trouvé.")
        return None
    product_index = matches[0]
    target = df.iloc[product_index]

    # On cherche plus de candidats avant de les reclasser
    n_query = max(100, n_recommendations + 1)
    distances, indices = model.kneighbors(
        feature_matrix[product_index].reshape(1, -1),
        n_neighbors=n_query
    )
    indices = indices.flatten()
    distances = distances.flatten()

    # Enlever le produit lui-même
    mask = indices != product_index
    indices = indices[mask]
    distances = distances[mask]

    recommendations = df.iloc[indices].copy()

    # Similarité basée sur les caractéristiques
    recommendations["content_similarity"] = 1 - distances

    # Similarité basée sur le prix (relative au prix du produit cible,
    # pas au range global du catalogue)
    target_price = target["price_usd"]
    recommendations["price_similarity"] = 1 - (
        abs(recommendations["price_usd"] - target_price)
        / max(target_price, 1)
    )
    recommendations["price_similarity"] = recommendations[
        "price_similarity"
    ].clip(lower=0)

    # Score final
    recommendations["final_score"] = (
        0.75 * recommendations["content_similarity"]
        + 0.25 * recommendations["price_similarity"]
    )

    recommendations = recommendations.sort_values(
        "final_score", ascending=False
    ).head(n_recommendations)

    return recommendations[[
        "product_id", "category", "subcategory", "material", "color",
        "season", "style", "size", "price_usd", "rating", "return_rate",
        "content_similarity", "price_similarity", "final_score"
    ]]

In [50]:
recommend_hybrid("WC000001")

,product_id,category,subcategory,material,color,season,style,size,price_usd,rating,return_rate,content_similarity,price_similarity,final_score
35477,WC035478,Jeans,Skinny Jeans,Denim,Navy,Summer,Business Casual,L,36.17,3.5,0.14,0.833333,0.977568,0.869392
46537,WC046538,Jeans,Skinny Jeans,Denim,Navy,Summer,Business Casual,M,35.79,0.0,0.16,0.833333,0.967297,0.866824
40777,WC040778,Jeans,Skinny Jeans,Denim,Pink,Summer,Business Casual,XS,34.57,4.1,0.11,0.833333,0.934324,0.858581
28618,WC028619,Jeans,Skinny Jeans,Denim,Navy,Summer,Business Casual,S,39.99,3.4,0.22,0.833333,0.919189,0.854797
40723,WC040724,Jeans,Skinny Jeans,Denim,Navy,Summer,Business Casual,L,40.62,4.5,0.12,0.833333,0.902162,0.850541

In [51]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
import tensorflow as tf
from tensorflow.keras import layers, Model
from sklearn.metrics.pairwise import cosine_similarity

# ---------------------------------------------------------
# 1. Préparation des features
# ---------------------------------------------------------
cat_features = ['category', 'subcategory', 'material', 'color', 'season', 'style', 'size']
num_features = ['price_usd', 'discount_percent', 'rating', 'return_rate']

encoders = {}
cat_data = {}
cat_dims = {}

for col in cat_features:
    le = LabelEncoder()
    cat_data[col] = le.fit_transform(df[col])
    encoders[col] = le
    cat_dims[col] = len(le.classes_)

scaler = StandardScaler()
num_data = scaler.fit_transform(df[num_features])

# ---------------------------------------------------------
# 2. Modèle : Embeddings catégoriels + features numériques -> Dense -> embedding produit
# ---------------------------------------------------------
EMBED_DIM_CAT = 8      # dimension des embeddings par variable catégorielle
PRODUCT_EMBED_DIM = 32  # dimension finale de l'embedding produit

cat_inputs = []
cat_embeds = []

for col in cat_features:
    inp = layers.Input(shape=(1,), name=f"input_{col}")
    emb = layers.Embedding(
        input_dim=cat_dims[col],
        output_dim=EMBED_DIM_CAT,
        name=f"embed_{col}"
    )(inp)
    emb = layers.Flatten()(emb)
    cat_inputs.append(inp)
    cat_embeds.append(emb)

num_input = layers.Input(shape=(len(num_features),), name="input_numerical")

x = layers.Concatenate()(cat_embeds + [num_input])
x = layers.Dense(128, activation="relu")(x)
x = layers.Dropout(0.2)(x)
x = layers.Dense(64, activation="relu")(x)
product_embedding = layers.Dense(
    PRODUCT_EMBED_DIM, activation=None, name="product_embedding"
)(x)

# Auto-encodeur : on force le modèle à reconstruire les features numériques
# à partir de l'embedding, pour que l'embedding soit informatif (pas besoin
# de labels externes = apprentissage non supervisé)
reconstruction = layers.Dense(len(num_features), activation=None, name="reconstruction")(product_embedding)

embedding_model = Model(inputs=cat_inputs + [num_input], outputs=product_embedding)
training_model = Model(inputs=cat_inputs + [num_input], outputs=reconstruction)

training_model.compile(optimizer="adam", loss="mse")

# ---------------------------------------------------------
# 3. Entraînement
# ---------------------------------------------------------
train_inputs = [cat_data[col].reshape(-1, 1) for col in cat_features] + [num_data]

training_model.fit(
    train_inputs,
    num_data,
    epochs=20,
    batch_size=256,
    validation_split=0.1,
    verbose=1
)

# ---------------------------------------------------------
# 4. Génération des embeddings produits
# ---------------------------------------------------------
product_embeddings = embedding_model.predict(train_inputs, batch_size=512)
print(product_embeddings.shape)  # (n_produits, PRODUCT_EMBED_DIM)

# ---------------------------------------------------------
# 5. Recommandation par cosine similarity sur les embeddings
# ---------------------------------------------------------
def recommend_nn(product_id, n_recommendations=5):
    matches = np.flatnonzero(df['product_id'].values == product_id)
    if len(matches) == 0:
        print("Produit non trouvé.")
        return None
    product_index = matches[0]

    target_vec = product_embeddings[product_index].reshape(1, -1)
    sims = cosine_similarity(target_vec, product_embeddings).flatten()

    # Exclure le produit lui-même
    sims[product_index] = -np.inf

    top_indices = np.argsort(sims)[::-1][:n_recommendations]

    recommendations = df.iloc[top_indices][[
        'product_id', 'category', 'subcategory', 'material', 'color',
        'season', 'style', 'size', 'price_usd', 'rating', 'return_rate'
    ]].copy()
    recommendations['similarity_score'] = sims[top_indices]

    return recommendations.reset_index(drop=True)

recommend_nn("WC000001")

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1786699461.583187      58 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13756 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
I0000 00:00:1786699461.586277      58 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 13756 MB memory:  -> device: 1, name: Tesla T4, pci bus id: 0000:00:05.0, compute capability: 7.5

Epoch 1/20
 61/176 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5003

I0000 00:00:1786699468.070563     205 device_compiler.h:196] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

176/176 ━━━━━━━━━━━━━━━━━━━━ 9s 21ms/step - loss: 0.0988 - val_loss: 0.0020
Epoch 2/20
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0183 - val_loss: 0.0013
Epoch 3/20
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0148 - val_loss: 0.0013
Epoch 4/20
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0135 - val_loss: 0.0012
Epoch 5/20
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0124 - val_loss: 0.0012
Epoch 6/20
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0116 - val_loss: 0.0010
Epoch 7/20
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0107 - val_loss: 0.0021
Epoch 8/20
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0100 - val_loss: 0.0018
Epoch 9/20
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0094 - val_loss: 0.0022
Epoch 10/20
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0087 - val_loss: 0.0021
Epoch 11/20
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0081 - val_loss: 0.0023
Epoch 12/20
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0077 - val_loss: 0.0030
Epoch 13/20
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0073 - val_loss: 0.0039
Epoch 14/20
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0068 - val_loss: 0.0043
Epoch 15/20
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0065 - val_loss: 0.0049
Epoch 16/20
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0061 - val_loss: 0.0061
Epoch 17/20
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0056 - val_loss: 0.0067
Epoch 18/20
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0053 - val_loss: 0.0090
Epoch 19/20
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0049 - val_loss: 0.0095
Epoch 20/20
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0047 - val_loss: 0.0114
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
(50000, 32)

,product_id,category,subcategory,material,color,season,style,size,price_usd,rating,return_rate,similarity_score
0,WC035870,Dresses,Maxi Dress,Viscose,Black,All Season,Streetwear,XXL,37.81,0.0,0.17,0.999924
1,WC027704,Jeans,Bootcut Jeans,Denim,Green,Spring,Elegant,S,38.77,0.0,0.17,0.999863
2,WC032296,Jeans,Straight Jeans,Denim,Purple,Spring,Business Casual,XL,35.18,0.0,0.17,0.999837
3,WC019726,Jeans,Wide-Leg Jeans,Denim,Gray,Spring,Bohemian,M,34.94,0.0,0.17,0.999746
4,WC006809,Dresses,Bodycon Dress,Cotton,Black,Summer,Streetwear,M,34.42,0.0,0.17,0.999690

In [52]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras import layers, Model, regularizers, callbacks
from sklearn.metrics.pairwise import cosine_similarity

# ===========================================================
# 1. Préparation des features (identique à avant)
# ===========================================================
cat_features = ['category', 'subcategory', 'material', 'color', 'season', 'style', 'size']
num_features = ['price_usd', 'discount_percent', 'rating', 'return_rate']

encoders = {}
cat_data = {}
cat_dims = {}

for col in cat_features:
    le = LabelEncoder()
    cat_data[col] = le.fit_transform(df[col])
    encoders[col] = le
    cat_dims[col] = len(le.classes_)

scaler = StandardScaler()
num_data = scaler.fit_transform(df[num_features])

all_inputs = [cat_data[col].reshape(-1, 1) for col in cat_features] + [num_data]
n_samples = len(df)

# Split train/val pour l'EarlyStopping
idx_train, idx_val = train_test_split(
    np.arange(n_samples), test_size=0.15, random_state=42
)

def subset(inputs, idx):
    return [arr[idx] for arr in inputs]

train_inputs = subset(all_inputs, idx_train)
val_inputs = subset(all_inputs, idx_val)
train_target = num_data[idx_train]
val_target = num_data[idx_val]

# ===========================================================
# 2. Autoencoder amélioré : bottleneck contraint + régularisation
# ===========================================================
EMBED_DIM_CAT = 8
BOTTLENECK_DIM = 16     # plus petit -> force une compression plus forte
L2_REG = 1e-4
DROPOUT_RATE = 0.3

cat_inputs = []
cat_embeds = []

for col in cat_features:
    inp = layers.Input(shape=(1,), name=f"input_{col}")
    emb = layers.Embedding(
        input_dim=cat_dims[col],
        output_dim=EMBED_DIM_CAT,
        embeddings_regularizer=regularizers.l2(L2_REG),
        name=f"embed_{col}"
    )(inp)
    emb = layers.Flatten()(emb)
    cat_inputs.append(inp)
    cat_embeds.append(emb)

num_input = layers.Input(shape=(len(num_features),), name="input_numerical")

# --- Encodeur ---
x = layers.Concatenate()(cat_embeds + [num_input])
x = layers.Dense(128, activation="relu", kernel_regularizer=regularizers.l2(L2_REG))(x)
x = layers.BatchNormalization()(x)
x = layers.Dropout(DROPOUT_RATE)(x)

x = layers.Dense(64, activation="relu", kernel_regularizer=regularizers.l2(L2_REG))(x)
x = layers.BatchNormalization()(x)
x = layers.Dropout(DROPOUT_RATE)(x)

# --- Bottleneck (l'embedding produit final) ---
bottleneck = layers.Dense(
    BOTTLENECK_DIM,
    activation=None,
    activity_regularizer=regularizers.l1(1e-5),  # encourage un embedding "sparse"/discriminant
    name="product_embedding"
)(x)

# --- Décodeur ---
d = layers.Dense(64, activation="relu", kernel_regularizer=regularizers.l2(L2_REG))(bottleneck)
d = layers.Dropout(DROPOUT_RATE)(d)
d = layers.Dense(128, activation="relu", kernel_regularizer=regularizers.l2(L2_REG))(d)
reconstruction = layers.Dense(len(num_features), activation=None, name="reconstruction")(d)

embedding_model = Model(inputs=cat_inputs + [num_input], outputs=bottleneck)
autoencoder = Model(inputs=cat_inputs + [num_input], outputs=reconstruction)

autoencoder.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3), loss="mse")

# ===========================================================
# 3. Entraînement avec EarlyStopping
# ===========================================================
early_stop = callbacks.EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

reduce_lr = callbacks.ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.5,
    patience=3,
    min_lr=1e-5
)

history = autoencoder.fit(
    train_inputs,
    train_target,
    validation_data=(val_inputs, val_target),
    epochs=100,
    batch_size=256,
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

# ===========================================================
# 4. Génération des embeddings produits (sur tout le dataset)
# ===========================================================
product_embeddings_ae = embedding_model.predict(all_inputs, batch_size=512)
print("Embedding shape:", product_embeddings_ae.shape)

# ===========================================================
# 5. Recommandation par cosine similarity (Deep Learning)
# ===========================================================
def recommend_autoencoder(product_id, n_recommendations=5):
    matches = np.flatnonzero(df['product_id'].values == product_id)
    if len(matches) == 0:
        print("Produit non trouvé.")
        return None
    product_index = matches[0]

    target_vec = product_embeddings_ae[product_index].reshape(1, -1)
    sims = cosine_similarity(target_vec, product_embeddings_ae).flatten()
    sims[product_index] = -np.inf

    top_indices = np.argsort(sims)[::-1][:n_recommendations]

    recommendations = df.iloc[top_indices][[
        'product_id', 'category', 'subcategory', 'material', 'color',
        'season', 'style', 'size', 'price_usd', 'rating', 'return_rate'
    ]].copy()
    recommendations['similarity_score'] = sims[top_indices]

    return recommendations.reset_index(drop=True)

# ===========================================================
# 6. Comparaison expérimentale : Hybrid KNN vs Autoencoder
# ===========================================================
def compare_recommendations(product_id, n_recommendations=5):
    print(f"=== Cible : {product_id} ===\n")

    print("--- Hybrid KNN (classique) ---")
    knn_res = recommend_hybrid(product_id, n_recommendations)
    print(knn_res[['product_id', 'category', 'subcategory', 'color', 'price_usd', 'final_score']])

    print("\n--- Autoencoder (Deep Learning) ---")
    ae_res = recommend_autoencoder(product_id, n_recommendations)
    print(ae_res[['product_id', 'category', 'subcategory', 'color', 'price_usd', 'similarity_score']])

    # Taux de recouvrement entre les deux listes
    overlap = set(knn_res['product_id']) & set(ae_res['product_id'])
    print(f"\nRecouvrement : {len(overlap)}/{n_recommendations} produits communs -> {overlap}")

    return knn_res, ae_res

compare_recommendations("WC000001")

Epoch 1/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 0.3350 - val_loss: 0.5282 - learning_rate: 0.0010
Epoch 2/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.1980 - val_loss: 0.2549 - learning_rate: 0.0010
Epoch 3/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.1669 - val_loss: 0.1379 - learning_rate: 0.0010
Epoch 4/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.1464 - val_loss: 0.0871 - learning_rate: 0.0010
Epoch 5/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.1328 - val_loss: 0.0784 - learning_rate: 0.0010
Epoch 6/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.1200 - val_loss: 0.0654 - learning_rate: 0.0010
Epoch 7/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.1109 - val_loss: 0.0659 - learning_rate: 0.0010
Epoch 8/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.1042 - val_loss: 0.0706 - learning_rate: 0.0010
Epoch 9/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0975 - val_loss: 0.0711 - learning_rate: 0.0010
Epoch 10/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0934 - val_loss: 0.0622 - learning_rate: 5.0000e-04
Epoch 11/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0897 - val_loss: 0.0594 - learning_rate: 5.0000e-04
Epoch 12/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0889 - val_loss: 0.0572 - learning_rate: 5.0000e-04
Epoch 13/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0861 - val_loss: 0.0620 - learning_rate: 5.0000e-04
Epoch 14/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0852 - val_loss: 0.0585 - learning_rate: 5.0000e-04
Epoch 15/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0826 - val_loss: 0.0595 - learning_rate: 5.0000e-04
Epoch 16/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0807 - val_loss: 0.0577 - learning_rate: 2.5000e-04
Epoch 17/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0793 - val_loss: 0.0584 - learning_rate: 2.5000e-04
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
Embedding shape: (50000, 16)
=== Cible : WC000001 ===

--- Hybrid KNN (classique) ---
      product_id category   subcategory color  price_usd  final_score
35477   WC035478    Jeans  Skinny Jeans  Navy      36.17     0.869392
46537   WC046538    Jeans  Skinny Jeans  Navy      35.79     0.866824
40777   WC040778    Jeans  Skinny Jeans  Pink      34.57     0.858581
28618   WC028619    Jeans  Skinny Jeans  Navy      39.99     0.854797
40723   WC040724    Jeans  Skinny Jeans  Navy      40.62     0.850541

--- Autoencoder (Deep Learning) ---
  product_id category     subcategory   color  price_usd  similarity_score
0   WC035870  Dresses      Maxi Dress   Black      37.81          0.999912
1   WC032296    Jeans  Straight Jeans  Purple      35.18          0.999799
2   WC027704    Jeans   Bootcut Jeans   Green      38.77          0.999767
3   WC019726    Jeans  Wide-Leg Jeans    Gray      34.94          0.999727
4   WC006809  Dresses   Bodycon Dress   Black      34.42          0.999560

Recouvrement : 0/5 produits communs -> set()

(      product_id category   subcategory material color  season  \
 35477   WC035478    Jeans  Skinny Jeans    Denim  Navy  Summer
 46537   WC046538    Jeans  Skinny Jeans    Denim  Navy  Summer
 40777   WC040778    Jeans  Skinny Jeans    Denim  Pink  Summer
 28618   WC028619    Jeans  Skinny Jeans    Denim  Navy  Summer
 40723   WC040724    Jeans  Skinny Jeans    Denim  Navy  Summer

                  style size  price_usd  rating  return_rate  \
 35477  Business Casual    L      36.17     3.5         0.14
 46537  Business Casual    M      35.79     0.0         0.16
 40777  Business Casual   XS      34.57     4.1         0.11
 28618  Business Casual    S      39.99     3.4         0.22
 40723  Business Casual    L      40.62     4.5         0.12

        content_similarity  price_similarity  final_score
 35477            0.833333          0.977568     0.869392
 46537            0.833333          0.967297     0.866824
 40777            0.833333          0.934324     0.858581
 28618            0.833333          0.919189     0.854797
 40723            0.833333          0.902162     0.850541  ,
   product_id category     subcategory material   color      season  \
 0   WC035870  Dresses      Maxi Dress  Viscose   Black  All Season
 1   WC032296    Jeans  Straight Jeans    Denim  Purple      Spring
 2   WC027704    Jeans   Bootcut Jeans    Denim   Green      Spring
 3   WC019726    Jeans  Wide-Leg Jeans    Denim    Gray      Spring
 4   WC006809  Dresses   Bodycon Dress   Cotton   Black      Summer

              style size  price_usd  rating  return_rate  similarity_score
 0       Streetwear  XXL      37.81     0.0         0.17          0.999912
 1  Business Casual   XL      35.18     0.0         0.17          0.999799
 2          Elegant    S      38.77     0.0         0.17          0.999767
 3         Bohemian    M      34.94     0.0         0.17          0.999727
 4       Streetwear    M      34.42     0.0         0.17          0.999560  )

In [53]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers, Model, regularizers, callbacks
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics.pairwise import cosine_similarity

# ===========================================================
# 1. Préparation des features (identique)
# ===========================================================
cat_features = ['category', 'subcategory', 'material', 'color', 'season', 'style', 'size']
num_features = ['price_usd', 'discount_percent', 'rating', 'return_rate']

encoders = {}
cat_data = {}
cat_dims = {}

for col in cat_features:
    le = LabelEncoder()
    cat_data[col] = le.fit_transform(df[col])
    encoders[col] = le
    cat_dims[col] = len(le.classes_)

scaler = StandardScaler()
num_data = scaler.fit_transform(df[num_features]).astype("float32")

n_samples = len(df)

# ===========================================================
# 2. Génération de triplets (anchor, positive, negative)
# ===========================================================
# Contrairement à l'autoencoder (tâche de reconstruction), ici on entraîne
# l'embedding directement sur une notion de similarité produit :
#   - positive = même category + subcategory (variante du même produit)
#   - negative = category différente (produit clairement différent)
# C'est un signal métier explicite, pas juste une compression de features.

rng = np.random.default_rng(42)

category_arr = df['category'].values
subcategory_arr = df['subcategory'].values

# Index des produits groupés par (category, subcategory) pour piocher des positifs
group_key = pd.Series(list(zip(category_arr, subcategory_arr)))
group_to_indices = group_key.groupby(group_key).apply(lambda s: s.index.to_numpy())

def build_triplets(n_triplets):
    anchors = rng.integers(0, n_samples, size=n_triplets)
    positives = np.empty(n_triplets, dtype=int)
    negatives = np.empty(n_triplets, dtype=int)

    for i, a in enumerate(anchors):
        key = (category_arr[a], subcategory_arr[a])
        same_group = group_to_indices[key]
        # positif : même groupe, différent du anchor si possible
        if len(same_group) > 1:
            p = rng.choice(same_group)
            while p == a:
                p = rng.choice(same_group)
        else:
            p = a
        positives[i] = p

        # négatif : catégorie différente
        n = rng.integers(0, n_samples)
        while category_arr[n] == category_arr[a]:
            n = rng.integers(0, n_samples)
        negatives[i] = n

    return anchors, positives, negatives

N_TRIPLETS = 100_000
anchor_idx, pos_idx, neg_idx = build_triplets(N_TRIPLETS)

# ===========================================================
# 3. Modèle d'embedding partagé (tour unique réutilisée 3x)
# ===========================================================
EMBED_DIM_CAT = 8
PRODUCT_EMBED_DIM = 32
L2_REG = 1e-4
DROPOUT_RATE = 0.2
MARGIN = 0.3  # marge du triplet loss

def build_embedding_tower():
    cat_inputs = [layers.Input(shape=(1,), name=f"input_{col}") for col in cat_features]
    cat_embeds = []
    for inp, col in zip(cat_inputs, cat_features):
        emb = layers.Embedding(
            input_dim=cat_dims[col],
            output_dim=EMBED_DIM_CAT,
            embeddings_regularizer=regularizers.l2(L2_REG),
            name=f"embed_{col}"
        )(inp)
        cat_embeds.append(layers.Flatten()(emb))

    num_input = layers.Input(shape=(len(num_features),), name="input_numerical")

    x = layers.Concatenate()(cat_embeds + [num_input])
    x = layers.Dense(128, activation="relu", kernel_regularizer=regularizers.l2(L2_REG))(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(DROPOUT_RATE)(x)
    x = layers.Dense(64, activation="relu", kernel_regularizer=regularizers.l2(L2_REG))(x)

    embedding = layers.Dense(PRODUCT_EMBED_DIM, activation=None, name="product_embedding")(x)
    embedding = layers.Lambda(
        lambda t: tf.math.l2_normalize(t, axis=1), name="l2_normalize"
    )(embedding)

    return Model(inputs=cat_inputs + [num_input], outputs=embedding, name="embedding_tower")

embedding_tower = build_embedding_tower()

# ===========================================================
# 4. Modèle triplet (3 branches partageant les mêmes poids)
# ===========================================================
def make_input_set(prefix):
    return [layers.Input(shape=(1,), name=f"{prefix}_{col}") for col in cat_features] + \
           [layers.Input(shape=(len(num_features),), name=f"{prefix}_numerical")]

anchor_inputs = make_input_set("anchor")
positive_inputs = make_input_set("positive")
negative_inputs = make_input_set("negative")

anchor_emb = embedding_tower(anchor_inputs)
positive_emb = embedding_tower(positive_inputs)
negative_emb = embedding_tower(negative_inputs)

merged = layers.Concatenate(axis=1)([anchor_emb, positive_emb, negative_emb])
triplet_model = Model(
    inputs=anchor_inputs + positive_inputs + negative_inputs,
    outputs=merged
)

def triplet_loss(y_true, y_pred, embed_dim=PRODUCT_EMBED_DIM, margin=MARGIN):
    a = y_pred[:, :embed_dim]
    p = y_pred[:, embed_dim:2*embed_dim]
    n = y_pred[:, 2*embed_dim:]
    pos_dist = tf.reduce_sum(tf.square(a - p), axis=1)
    neg_dist = tf.reduce_sum(tf.square(a - n), axis=1)
    loss = tf.maximum(pos_dist - neg_dist + margin, 0.0)
    return tf.reduce_mean(loss)

triplet_model.compile(optimizer=tf.keras.optimizers.Adam(1e-3), loss=triplet_loss)

# ===========================================================
# 5. Préparation des tenseurs d'entrée pour les triplets
# ===========================================================
def gather_inputs(indices):
    return [cat_data[col][indices].reshape(-1, 1) for col in cat_features] + [num_data[indices]]

train_data = (
    gather_inputs(anchor_idx) + gather_inputs(pos_idx) + gather_inputs(neg_idx)
)
dummy_y = np.zeros((N_TRIPLETS, 1))  # y_true inutilisé, la loss dépend seulement de y_pred

# ===========================================================
# 6. Entraînement avec EarlyStopping
# ===========================================================
early_stop = callbacks.EarlyStopping(monitor="loss", patience=4, restore_best_weights=True)
reduce_lr = callbacks.ReduceLROnPlateau(monitor="loss", factor=0.5, patience=2, min_lr=1e-5)

history = triplet_model.fit(
    train_data,
    dummy_y,
    epochs=30,
    batch_size=512,
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

# ===========================================================
# 7. Génération des embeddings produits finaux
# ===========================================================
all_inputs = [cat_data[col].reshape(-1, 1) for col in cat_features] + [num_data]
product_embeddings_nn = embedding_tower.predict(all_inputs, batch_size=1024)
print("Embedding shape:", product_embeddings_nn.shape)

# ===========================================================
# 8. Recommandation par cosine similarity (Neural Embedding)
# ===========================================================
def recommend_neural_embedding(product_id, n_recommendations=5):
    matches = np.flatnonzero(df['product_id'].values == product_id)
    if len(matches) == 0:
        print("Produit non trouvé.")
        return None
    product_index = matches[0]

    target_vec = product_embeddings_nn[product_index].reshape(1, -1)
    sims = cosine_similarity(target_vec, product_embeddings_nn).flatten()
    sims[product_index] = -np.inf

    top_indices = np.argsort(sims)[::-1][:n_recommendations]

    recommendations = df.iloc[top_indices][[
        'product_id', 'category', 'subcategory', 'material', 'color',
        'season', 'style', 'size', 'price_usd', 'rating', 'return_rate'
    ]].copy()
    recommendations['similarity_score'] = sims[top_indices]

    return recommendations.reset_index(drop=True)

# ===========================================================
# 9. Comparaison à 3 : Hybrid KNN vs Autoencoder vs Neural Embedding
# ===========================================================
def compare_all(product_id, n_recommendations=5):
    print(f"=== Cible : {product_id} ===\n")

    knn_res = recommend_hybrid(product_id, n_recommendations)
    ae_res = recommend_autoencoder(product_id, n_recommendations)
    nn_res = recommend_neural_embedding(product_id, n_recommendations)

    print("--- Hybrid KNN ---")
    print(knn_res[['product_id', 'subcategory', 'color', 'price_usd']])
    print("\n--- Autoencoder ---")
    print(ae_res[['product_id', 'subcategory', 'color', 'price_usd']])
    print("\n--- Neural Embedding (triplet loss) ---")
    print(nn_res[['product_id', 'subcategory', 'color', 'price_usd']])

    knn_set, ae_set, nn_set = set(knn_res['product_id']), set(ae_res['product_id']), set(nn_res['product_id'])
    print(f"\nRecouvrement KNN ∩ AE  : {knn_set & ae_set}")
    print(f"Recouvrement KNN ∩ NN  : {knn_set & nn_set}")
    print(f"Recouvrement AE  ∩ NN  : {ae_set & nn_set}")

    return knn_res, ae_res, nn_res

compare_all("WC000001")

Epoch 1/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 15s 28ms/step - loss: 0.0952 - learning_rate: 0.0010
Epoch 2/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0176 - learning_rate: 0.0010
Epoch 3/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0133 - learning_rate: 0.0010
Epoch 4/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0105 - learning_rate: 0.0010
Epoch 5/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0085 - learning_rate: 0.0010
Epoch 6/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0069 - learning_rate: 0.0010
Epoch 7/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0055 - learning_rate: 0.0010
Epoch 8/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0045 - learning_rate: 0.0010
Epoch 9/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0036 - learning_rate: 0.0010
Epoch 10/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0030 - learning_rate: 0.0010
Epoch 11/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0024 - learning_rate: 0.0010
Epoch 12/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0019 - learning_rate: 0.0010
Epoch 13/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0017 - learning_rate: 0.0010
Epoch 14/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0014 - learning_rate: 0.0010
Epoch 15/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0013 - learning_rate: 0.0010
Epoch 16/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0010 - learning_rate: 0.0010
Epoch 17/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0010 - learning_rate: 0.0010
Epoch 18/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.9964e-04 - learning_rate: 0.0010
Epoch 19/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9671e-04 - learning_rate: 0.0010
Epoch 20/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1420e-04 - learning_rate: 0.0010
Epoch 21/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7504e-04 - learning_rate: 0.0010
Epoch 22/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2978e-04 - learning_rate: 0.0010
Epoch 23/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7836e-04 - learning_rate: 0.0010
Epoch 24/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.3916e-04 - learning_rate: 5.0000e-04
Epoch 25/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4.6652e-04 - learning_rate: 5.0000e-04
Epoch 26/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4.5421e-04 - learning_rate: 5.0000e-04
Epoch 27/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3.9653e-04 - learning_rate: 2.5000e-04
Epoch 28/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3.5652e-04 - learning_rate: 2.5000e-04
Epoch 29/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3.2892e-04 - learning_rate: 2.5000e-04
Epoch 30/30
196/196 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3.0709e-04 - learning_rate: 1.2500e-04
49/49 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step
Embedding shape: (50000, 32)
=== Cible : WC000001 ===

--- Hybrid KNN ---
      product_id   subcategory color  price_usd
35477   WC035478  Skinny Jeans  Navy      36.17
46537   WC046538  Skinny Jeans  Navy      35.79
40777   WC040778  Skinny Jeans  Pink      34.57
28618   WC028619  Skinny Jeans  Navy      39.99
40723   WC040724  Skinny Jeans  Navy      40.62

--- Autoencoder ---
  product_id     subcategory   color  price_usd
0   WC035870      Maxi Dress   Black      37.81
1   WC032296  Straight Jeans  Purple      35.18
2   WC027704   Bootcut Jeans   Green      38.77
3   WC019726  Wide-Leg Jeans    Gray      34.94
4   WC006809   Bodycon Dress   Black      34.42

--- Neural Embedding (triplet loss) ---
  product_id     subcategory   color  price_usd
0   WC019726  Wide-Leg Jeans    Gray      34.94
1   WC041345    Skinny Jeans   Black      41.47
2   WC041598    Skinny Jeans   Beige      30.56
3   WC003568  Straight Jeans   Black      32.66
4   WC032296  Straight Jeans  Purple      35.18

Recouvrement KNN ∩ AE  : set()
Recouvrement KNN ∩ NN  : set()
Recouvrement AE  ∩ NN  : {'WC019726', 'WC032296'}

(      product_id category   subcategory material color  season  \
 35477   WC035478    Jeans  Skinny Jeans    Denim  Navy  Summer
 46537   WC046538    Jeans  Skinny Jeans    Denim  Navy  Summer
 40777   WC040778    Jeans  Skinny Jeans    Denim  Pink  Summer
 28618   WC028619    Jeans  Skinny Jeans    Denim  Navy  Summer
 40723   WC040724    Jeans  Skinny Jeans    Denim  Navy  Summer

                  style size  price_usd  rating  return_rate  \
 35477  Business Casual    L      36.17     3.5         0.14
 46537  Business Casual    M      35.79     0.0         0.16
 40777  Business Casual   XS      34.57     4.1         0.11
 28618  Business Casual    S      39.99     3.4         0.22
 40723  Business Casual    L      40.62     4.5         0.12

        content_similarity  price_similarity  final_score
 35477            0.833333          0.977568     0.869392
 46537            0.833333          0.967297     0.866824
 40777            0.833333          0.934324     0.858581
 28618            0.833333          0.919189     0.854797
 40723            0.833333          0.902162     0.850541  ,
   product_id category     subcategory material   color      season  \
 0   WC035870  Dresses      Maxi Dress  Viscose   Black  All Season
 1   WC032296    Jeans  Straight Jeans    Denim  Purple      Spring
 2   WC027704    Jeans   Bootcut Jeans    Denim   Green      Spring
 3   WC019726    Jeans  Wide-Leg Jeans    Denim    Gray      Spring
 4   WC006809  Dresses   Bodycon Dress   Cotton   Black      Summer

              style size  price_usd  rating  return_rate  similarity_score
 0       Streetwear  XXL      37.81     0.0         0.17          0.999912
 1  Business Casual   XL      35.18     0.0         0.17          0.999799
 2          Elegant    S      38.77     0.0         0.17          0.999767
 3         Bohemian    M      34.94     0.0         0.17          0.999727
 4       Streetwear    M      34.42     0.0         0.17          0.999560  ,
   product_id category     subcategory material   color      season  \
 0   WC019726    Jeans  Wide-Leg Jeans    Denim    Gray      Spring
 1   WC041345    Jeans    Skinny Jeans    Denim   Black      Spring
 2   WC041598    Jeans    Skinny Jeans    Denim   Beige      Spring
 3   WC003568    Jeans  Straight Jeans    Denim   Black  All Season
 4   WC032296    Jeans  Straight Jeans    Denim  Purple      Spring

              style size  price_usd  rating  return_rate  similarity_score
 0         Bohemian    M      34.94     0.0         0.17          0.999994
 1       Minimalist    M      41.47     0.0         0.17          0.999945
 2         Bohemian    M      30.56     0.0         0.17          0.999924
 3         Bohemian    M      32.66     0.0         0.17          0.999880
 4  Business Casual   XL      35.18     0.0         0.17          0.999860  )

In [55]:

# ===========================================================
# FIX 1 — Autoencoder : reconstruire AUSSI le catégoriel
# ===========================================================
d = layers.Dense(64, activation="relu", kernel_regularizer=regularizers.l2(L2_REG))(bottleneck)
d = layers.Dropout(DROPOUT_RATE)(d)
d = layers.Dense(128, activation="relu", kernel_regularizer=regularizers.l2(L2_REG))(d)

# une tête softmax par variable catégorielle + une tête numérique
outputs = []
losses = {}
loss_weights = {}

for col in cat_features:
    out = layers.Dense(cat_dims[col], activation="softmax", name=f"recon_{col}")(d)
    outputs.append(out)
    losses[f"recon_{col}"] = "sparse_categorical_crossentropy"
    loss_weights[f"recon_{col}"] = 1.0

num_out = layers.Dense(len(num_features), activation=None, name="recon_numerical")(d)
outputs.append(num_out)
losses["recon_numerical"] = "mse"
loss_weights["recon_numerical"] = 1.0  # à ajuster : le num pèse sinon trop peu vs 7 têtes catégorielles

embedding_model = Model(inputs=cat_inputs + [num_input], outputs=bottleneck)
autoencoder = Model(inputs=cat_inputs + [num_input], outputs=outputs)
autoencoder.compile(optimizer=tf.keras.optimizers.Adam(1e-3), loss=losses, loss_weights=loss_weights)

train_targets = {f"recon_{col}": cat_data[col][idx_train] for col in cat_features}
train_targets["recon_numerical"] = train_target

val_targets = {f"recon_{col}": cat_data[col][idx_val] for col in cat_features}
val_targets["recon_numerical"] = val_target

autoencoder.fit(train_inputs, train_targets,
                 validation_data=(val_inputs, val_targets),
                 epochs=100, batch_size=256,
                 callbacks=[early_stop, reduce_lr], verbose=1)

Epoch 1/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 22s 59ms/step - loss: 14.5986 - recon_category_loss: 1.7979 - recon_color_loss: 2.3544 - recon_material_loss: 1.7841 - recon_numerical_loss: 0.3569 - recon_season_loss: 1.4797 - recon_size_loss: 1.6571 - recon_style_loss: 1.8521 - recon_subcategory_loss: 3.2592 - val_loss: 11.4863 - val_recon_category_loss: 0.8431 - val_recon_color_loss: 2.2931 - val_recon_material_loss: 1.3085 - val_recon_numerical_loss: 0.2867 - val_recon_season_loss: 1.2310 - val_recon_size_loss: 1.5598 - val_recon_style_loss: 1.5755 - val_recon_subcategory_loss: 2.3327 - learning_rate: 0.0010
Epoch 2/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.4810 - recon_category_loss: 0.5491 - recon_color_loss: 2.3314 - recon_material_loss: 1.2626 - recon_numerical_loss: 0.4834 - recon_season_loss: 1.0253 - recon_size_loss: 1.4215 - recon_style_loss: 1.3895 - recon_subcategory_loss: 1.9988 - val_loss: 8.5291 - val_recon_category_loss: 0.1778 - val_recon_color_loss: 2.3007 - val_recon_material_loss: 1.0768 - val_recon_numerical_loss: 0.4384 - val_recon_season_loss: 0.7575 - val_recon_size_loss: 1.0404 - val_recon_style_loss: 1.1164 - val_recon_subcategory_loss: 1.5618 - learning_rate: 0.0010
Epoch 3/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.1324 - recon_category_loss: 0.3016 - recon_color_loss: 2.3244 - recon_material_loss: 1.1497 - recon_numerical_loss: 0.5533 - recon_season_loss: 0.8349 - recon_size_loss: 1.0559 - recon_style_loss: 1.1691 - recon_subcategory_loss: 1.6752 - val_loss: 7.6761 - val_recon_category_loss: 0.1093 - val_recon_color_loss: 2.3010 - val_recon_material_loss: 1.0017 - val_recon_numerical_loss: 0.3905 - val_recon_season_loss: 0.6275 - val_recon_size_loss: 0.8064 - val_recon_style_loss: 0.9454 - val_recon_subcategory_loss: 1.4287 - learning_rate: 5.0000e-04
Epoch 4/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.6544 - recon_category_loss: 0.2674 - recon_color_loss: 2.3313 - recon_material_loss: 1.0800 - recon_numerical_loss: 0.5557 - recon_season_loss: 0.7778 - recon_size_loss: 0.9133 - recon_style_loss: 1.0512 - recon_subcategory_loss: 1.6077 - val_loss: 7.1251 - val_recon_category_loss: 0.0814 - val_recon_color_loss: 2.2946 - val_recon_material_loss: 0.8718 - val_recon_numerical_loss: 0.4004 - val_recon_season_loss: 0.5561 - val_recon_size_loss: 0.6615 - val_recon_style_loss: 0.8246 - val_recon_subcategory_loss: 1.3640 - learning_rate: 5.0000e-04

In [60]:
# ===========================================================
# FIX 2 — Triplet : négatifs durs (même category, autre subcategory)
# ===========================================================
subcat_group_key = pd.Series(list(zip(category_arr, subcategory_arr)))
category_series = pd.Series(category_arr)
category_to_indices = category_series.groupby(category_series).apply(lambda s: s.index.to_numpy())

def build_triplets_hard(n_triplets, hard_ratio=0.7):
    anchors = rng.integers(0, n_samples, size=n_triplets)
    positives = np.empty(n_triplets, dtype=int)
    negatives = np.empty(n_triplets, dtype=int)

    for i, a in enumerate(anchors):
        key = (category_arr[a], subcategory_arr[a])
        same_group = group_to_indices[key]
        p = rng.choice(same_group)
        while p == a and len(same_group) > 1:
            p = rng.choice(same_group)
        positives[i] = p

        if rng.random() < hard_ratio:
            # négatif dur : même category, autre subcategory
            same_cat = category_to_indices[category_arr[a]]
            n = rng.choice(same_cat)
            tries = 0
            while subcategory_arr[n] == subcategory_arr[a] and tries < 20:
                n = rng.choice(same_cat)
                tries += 1
        else:
            # négatif facile : autre category (garde un peu de diversité de gradient)
            n = rng.integers(0, n_samples)
            while category_arr[n] == category_arr[a]:
                n = rng.integers(0, n_samples)
        negatives[i] = n

    return anchors, positives, negatives

anchor_idx, pos_idx, neg_idx = build_triplets_hard(150_000, hard_ratio=0.7)
# régénérer train_data avec ces nouveaux triplets, réentraîner

In [61]:
def check_embedding_health(embeddings, name):
    norms = np.linalg.norm(embeddings, axis=1)
    pairwise_sample = cosine_similarity(embeddings[:500])
    off_diag = pairwise_sample[~np.eye(500, dtype=bool)]
    print(f"[{name}] std par dimension (moyenne): {embeddings.std(axis=0).mean():.4f}")
    print(f"[{name}] similarité cosine moyenne (paires aléatoires): {off_diag.mean():.4f}")
    print(f"[{name}] similarité cosine std: {off_diag.std():.4f}")
    # proche de 1.0 en moyenne avec std faible = collapse

check_embedding_health(product_embeddings_ae, "Autoencoder")
check_embedding_health(product_embeddings_nn, "Neural Embedding")

[Autoencoder] std par dimension (moyenne): 0.4167
[Autoencoder] similarité cosine moyenne (paires aléatoires): 0.0162
[Autoencoder] similarité cosine std: 0.4567
[Neural Embedding] std par dimension (moyenne): 0.1686
[Neural Embedding] similarité cosine moyenne (paires aléatoires): 0.0380
[Neural Embedding] similarité cosine std: 0.4537

In [62]:
def evaluate_model(recommend_fn, n_products=200, k=5):
    sample_ids = df['product_id'].sample(n_products, random_state=42).values
    cat_match, subcat_match, price_ratios = [], [], []

    for pid in sample_ids:
        target_row = df[df['product_id'] == pid].iloc[0]
        recs = recommend_fn(pid, k)
        if recs is None or len(recs) == 0:
            continue
        cat_match.append((recs['category'] == target_row['category']).mean())
        subcat_match.append((recs['subcategory'] == target_row['subcategory']).mean())
        price_ratios.append((abs(recs['price_usd'] - target_row['price_usd']) / max(target_row['price_usd'], 1)).mean())

    print(f"Category match@{k}: {np.mean(cat_match):.3f}")
    print(f"Subcategory match@{k}: {np.mean(subcat_match):.3f}")
    print(f"Écart prix relatif moyen: {np.mean(price_ratios):.3f}")

print("--- Hybrid KNN ---"); evaluate_model(lambda pid, k: recommend_hybrid(pid, k))
print("--- Autoencoder ---"); evaluate_model(lambda pid, k: recommend_autoencoder(pid, k))
print("--- Neural Embedding ---"); evaluate_model(lambda pid, k: recommend_neural_embedding(pid, k))

--- Hybrid KNN ---
Category match@5: 0.998
Subcategory match@5: 0.928
Écart prix relatif moyen: 0.121
--- Autoencoder ---
Category match@5: 0.262
Subcategory match@5: 0.059
Écart prix relatif moyen: 0.041
--- Neural Embedding ---
Category match@5: 1.000
Subcategory match@5: 0.542
Écart prix relatif moyen: 0.070

In [63]:
# ===========================================================
# A. NEURAL EMBEDDING — marge réduite + négatifs 100% durs
# ===========================================================

MARGIN = 0.1  # réduit de 0.3 -> force une séparation plus fine

def build_triplets_hard_v2(n_triplets):
    anchors = rng.integers(0, n_samples, size=n_triplets)
    positives = np.empty(n_triplets, dtype=int)
    negatives = np.empty(n_triplets, dtype=int)
    skipped_self_positive = 0

    for i, a in enumerate(anchors):
        key = (category_arr[a], subcategory_arr[a])
        same_group = group_to_indices[key]

        if len(same_group) > 1:
            p = rng.choice(same_group)
            tries = 0
            while p == a and tries < 10:
                p = rng.choice(same_group)
                tries += 1
        else:
            # groupe trop petit : on tolère anchor==positive mais on le compte
            p = a
            skipped_self_positive += 1
        positives[i] = p

        # négatif 100% dur : même category, subcategory différente
        same_cat = category_to_indices[category_arr[a]]
        n = rng.choice(same_cat)
        tries = 0
        while subcategory_arr[n] == subcategory_arr[a] and tries < 30:
            n = rng.choice(same_cat)
            tries += 1
        negatives[i] = n

    print(f"Triplets anchor==positive (groupe trop petit): {skipped_self_positive}/{n_triplets}")
    return anchors, positives, negatives

N_TRIPLETS = 200_000  # augmenté pour mieux couvrir les paires de subcategories
anchor_idx, pos_idx, neg_idx = build_triplets_hard_v2(N_TRIPLETS)

# Vérif rapide de couverture par subcategory (diagnostic)
subcat_coverage = pd.Series(subcategory_arr[anchor_idx]).value_counts()
print("Couverture triplets par subcategory (min/max):", subcat_coverage.min(), subcat_coverage.max())

train_data = gather_inputs(anchor_idx) + gather_inputs(pos_idx) + gather_inputs(neg_idx)
dummy_y = np.zeros((N_TRIPLETS, 1))

# Réinitialiser le modèle (nouveaux poids, pas de warm start sur l'ancienne marge)
embedding_tower = build_embedding_tower()
anchor_emb = embedding_tower(anchor_inputs)
positive_emb = embedding_tower(positive_inputs)
negative_emb = embedding_tower(negative_inputs)
merged = layers.Concatenate(axis=1)([anchor_emb, positive_emb, negative_emb])
triplet_model = Model(inputs=anchor_inputs + positive_inputs + negative_inputs, outputs=merged)

def triplet_loss_v2(y_true, y_pred, embed_dim=PRODUCT_EMBED_DIM, margin=MARGIN):
    a = y_pred[:, :embed_dim]
    p = y_pred[:, embed_dim:2*embed_dim]
    n = y_pred[:, 2*embed_dim:]
    pos_dist = tf.reduce_sum(tf.square(a - p), axis=1)
    neg_dist = tf.reduce_sum(tf.square(a - n), axis=1)
    loss = tf.maximum(pos_dist - neg_dist + margin, 0.0)
    return tf.reduce_mean(loss)

triplet_model.compile(optimizer=tf.keras.optimizers.Adam(1e-3), loss=triplet_loss_v2)

early_stop = callbacks.EarlyStopping(monitor="loss", patience=5, restore_best_weights=True)
reduce_lr = callbacks.ReduceLROnPlateau(monitor="loss", factor=0.5, patience=2, min_lr=1e-5)

history_nn = triplet_model.fit(
    train_data, dummy_y,
    epochs=40, batch_size=512,
    callbacks=[early_stop, reduce_lr], verbose=1
)

product_embeddings_nn = embedding_tower.predict(all_inputs, batch_size=1024)

check_embedding_health(product_embeddings_nn, "Neural Embedding v2")
print("--- Neural Embedding v2 ---")
evaluate_model(lambda pid, k: recommend_neural_embedding(pid, k))

Triplets anchor==positive (groupe trop petit): 0/200000
Couverture triplets par subcategory (min/max): 1875 6091
Epoch 1/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 15s 16ms/step - loss: 0.0525 - learning_rate: 0.0010
Epoch 2/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0098 - learning_rate: 0.0010
Epoch 3/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0062 - learning_rate: 0.0010
Epoch 4/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0038 - learning_rate: 0.0010
Epoch 5/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0023 - learning_rate: 0.0010
Epoch 6/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0015 - learning_rate: 0.0010
Epoch 7/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0011 - learning_rate: 0.0010
Epoch 8/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 8.1685e-04 - learning_rate: 0.0010
Epoch 9/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.2474e-04 - learning_rate: 0.0010
Epoch 10/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.5309e-04 - learning_rate: 0.0010
Epoch 11/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4.3370e-04 - learning_rate: 0.0010
Epoch 12/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4.7128e-04 - learning_rate: 0.0010
Epoch 13/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 3.3865e-04 - learning_rate: 0.0010
Epoch 14/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 2.6793e-04 - learning_rate: 5.0000e-04
Epoch 15/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 1.9400e-04 - learning_rate: 5.0000e-04
Epoch 16/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 2.2327e-04 - learning_rate: 5.0000e-04
Epoch 17/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 2.0689e-04 - learning_rate: 2.5000e-04
Epoch 18/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 1.6583e-04 - learning_rate: 2.5000e-04
Epoch 19/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 1.4872e-04 - learning_rate: 2.5000e-04
Epoch 20/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 1.4071e-04 - learning_rate: 2.5000e-04
Epoch 21/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 1.2130e-04 - learning_rate: 1.2500e-04
Epoch 22/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 1.0894e-04 - learning_rate: 1.2500e-04
Epoch 23/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 9.7806e-05 - learning_rate: 6.2500e-05
Epoch 24/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 9.2059e-05 - learning_rate: 6.2500e-05
Epoch 25/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 8.6197e-05 - learning_rate: 3.1250e-05
Epoch 26/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 8.1979e-05 - learning_rate: 3.1250e-05
Epoch 27/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 8.0187e-05 - learning_rate: 1.5625e-05
Epoch 28/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.8082e-05 - learning_rate: 1.5625e-05
Epoch 29/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.5902e-05 - learning_rate: 1.0000e-05
Epoch 30/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.3591e-05 - learning_rate: 1.0000e-05
Epoch 31/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.3432e-05 - learning_rate: 1.0000e-05
Epoch 32/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.1783e-05 - learning_rate: 1.0000e-05
Epoch 33/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.8718e-05 - learning_rate: 1.0000e-05
Epoch 34/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.9093e-05 - learning_rate: 1.0000e-05
Epoch 35/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.6630e-05 - learning_rate: 1.0000e-05
Epoch 36/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.4177e-05 - learning_rate: 1.0000e-05
Epoch 37/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.3873e-05 - learning_rate: 1.0000e-05
Epoch 38/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.2897e-05 - learning_rate: 1.0000e-05
Epoch 39/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.1270e-05 - learning_rate: 1.0000e-05
Epoch 40/40
391/391 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.9698e-05 - learning_rate: 1.0000e-05
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step
[Neural Embedding v2] std par dimension (moyenne): 0.0782
[Neural Embedding v2] similarité cosine moyenne (paires aléatoires): 0.7642
[Neural Embedding v2] similarité cosine std: 0.1779
--- Neural Embedding v2 ---
Category match@5: 0.993
Subcategory match@5: 0.996
Écart prix relatif moyen: 0.155

In [65]:
# ===========================================================
# B. AUTOENCODER — logging des losses par tête + capacité augmentée
# ===========================================================

BOTTLENECK_DIM = 32  # augmenté de 16 -> plus de capacité pour porter 8 signaux

cat_inputs = []
cat_embeds = []

for col in cat_features:
    inp = layers.Input(shape=(1,), name=f"input_{col}")
    emb = layers.Embedding(
        input_dim=cat_dims[col],
        output_dim=EMBED_DIM_CAT,
        embeddings_regularizer=regularizers.l2(L2_REG),
        name=f"embed_{col}"
    )(inp)
    emb = layers.Flatten()(emb)
    cat_inputs.append(inp)
    cat_embeds.append(emb)

num_input = layers.Input(shape=(len(num_features),), name="input_numerical")

x = layers.Concatenate()(cat_embeds + [num_input])
x = layers.Dense(128, activation="relu", kernel_regularizer=regularizers.l2(L2_REG))(x)
x = layers.BatchNormalization()(x)
x = layers.Dropout(DROPOUT_RATE)(x)
x = layers.Dense(64, activation="relu", kernel_regularizer=regularizers.l2(L2_REG))(x)
x = layers.BatchNormalization()(x)
x = layers.Dropout(DROPOUT_RATE)(x)

# Bottleneck sans activity_regularizer L1 cette fois (isolé pour diagnostic)
bottleneck = layers.Dense(
    BOTTLENECK_DIM,
    activation=None,
    name="product_embedding"
)(x)

d = layers.Dense(64, activation="relu", kernel_regularizer=regularizers.l2(L2_REG))(bottleneck)
d = layers.Dropout(DROPOUT_RATE)(d)
d = layers.Dense(128, activation="relu", kernel_regularizer=regularizers.l2(L2_REG))(d)

outputs = []
losses = {}
loss_weights = {}
metrics = {}

for col in cat_features:
    out = layers.Dense(cat_dims[col], activation="softmax", name=f"recon_{col}")(d)
    outputs.append(out)
    losses[f"recon_{col}"] = "sparse_categorical_crossentropy"
    metrics[f"recon_{col}"] = "accuracy"
    # poids proportionnel au nb de classes, cast explicite en float Python
    # pour éviter un mismatch de dtype (float64 numpy vs float32 Keras)
    loss_weights[f"recon_{col}"] = float(np.log1p(cat_dims[col]))

num_out = layers.Dense(len(num_features), activation=None, name="recon_numerical")(d)
outputs.append(num_out)
losses["recon_numerical"] = "mse"
loss_weights["recon_numerical"] = 0.5  # moins prioritaire que le catégoriel

embedding_model = Model(inputs=cat_inputs + [num_input], outputs=bottleneck)
autoencoder = Model(inputs=cat_inputs + [num_input], outputs=outputs)
autoencoder.compile(
    optimizer=tf.keras.optimizers.Adam(1e-3),
    loss=losses,
    loss_weights=loss_weights,
    metrics=metrics
)

train_targets = {f"recon_{col}": cat_data[col][idx_train] for col in cat_features}
train_targets["recon_numerical"] = train_target
val_targets = {f"recon_{col}": cat_data[col][idx_val] for col in cat_features}
val_targets["recon_numerical"] = val_target

early_stop = callbacks.EarlyStopping(monitor="val_loss", patience=6, restore_best_weights=True)
reduce_lr = callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=3, min_lr=1e-5)

history_ae = autoencoder.fit(
    train_inputs, train_targets,
    validation_data=(val_inputs, val_targets),
    epochs=100, batch_size=256,
    callbacks=[early_stop, reduce_lr], verbose=1
)

# Diagnostic : accuracy de reconstruction par variable (val)
print("\n--- Accuracy de reconstruction par variable (val) ---")
for col in cat_features:
    acc_key = f"val_recon_{col}_accuracy"
    if acc_key in history_ae.history:
        print(f"{col}: {history_ae.history[acc_key][-1]:.3f}")

product_embeddings_ae = embedding_model.predict(all_inputs, batch_size=512)
check_embedding_health(product_embeddings_ae, "Autoencoder v2")
print("--- Autoencoder v2 ---")
evaluate_model(lambda pid, k: recommend_autoencoder(pid, k))

Epoch 1/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 24s 66ms/step - loss: 35.9188 - recon_category_accuracy: 0.5160 - recon_category_loss: 1.4900 - recon_color_accuracy: 0.1784 - recon_color_loss: 2.3805 - recon_material_accuracy: 0.4462 - recon_material_loss: 1.5486 - recon_numerical_loss: 0.8085 - recon_season_accuracy: 0.3172 - recon_season_loss: 1.5037 - recon_size_accuracy: 0.3075 - recon_size_loss: 1.6803 - recon_style_accuracy: 0.3331 - recon_style_loss: 1.7124 - recon_subcategory_accuracy: 0.1659 - recon_subcategory_loss: 2.9478 - val_loss: 30.1405 - val_recon_category_accuracy: 0.8736 - val_recon_category_loss: 0.8623 - val_recon_color_accuracy: 0.2189 - val_recon_color_loss: 2.3463 - val_recon_material_accuracy: 0.7111 - val_recon_material_loss: 1.2293 - val_recon_numerical_loss: 0.8191 - val_recon_season_accuracy: 0.4061 - val_recon_season_loss: 1.4341 - val_recon_size_accuracy: 0.3692 - val_recon_size_loss: 1.6210 - val_recon_style_accuracy: 0.4511 - val_recon_style_loss: 1.5504 - val_recon_subcategory_accuracy: 0.4035 - val_recon_subcategory_loss: 2.2885 - learning_rate: 0.0010
Epoch 2/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 20.6471 - recon_category_accuracy: 0.9336 - recon_category_loss: 0.2164 - recon_color_accuracy: 0.2673 - recon_color_loss: 2.1479 - recon_material_accuracy: 0.7272 - recon_material_loss: 0.7235 - recon_numerical_loss: 0.9015 - recon_season_accuracy: 0.4044 - recon_season_loss: 1.3435 - recon_size_accuracy: 0.4954 - recon_size_loss: 1.3159 - recon_style_accuracy: 0.4482 - recon_style_loss: 1.3547 - recon_subcategory_accuracy: 0.5888 - recon_subcategory_loss: 1.0954 - val_loss: 15.8326 - val_recon_category_accuracy: 0.9984 - val_recon_category_loss: 0.0489 - val_recon_color_accuracy: 0.4209 - val_recon_color_loss: 1.7991 - val_recon_material_accuracy: 0.8171 - val_recon_material_loss: 0.5309 - val_recon_numerical_loss: 0.8015 - val_recon_season_accuracy: 0.4601 - val_recon_season_loss: 1.2387 - val_recon_size_accuracy: 0.6573 - val_recon_size_loss: 1.0163 - val_recon_style_accuracy: 0.4884 - val_recon_style_loss: 1.2375 - val_recon_subcategory_accuracy: 0.8684 - val_recon_subcategory_loss: 0.6094 - learning_rate: 0.0010
Epoch 3/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 15.5984 - recon_category_accuracy: 0.9499 - recon_category_loss: 0.1465 - recon_color_accuracy: 0.4731 - recon_color_loss: 1.5504 - recon_material_accuracy: 0.7519 - recon_material_loss: 0.6455 - recon_numerical_loss: 0.9252 - recon_season_accuracy: 0.4831 - recon_season_loss: 1.1943 - recon_size_accuracy: 0.5996 - recon_size_loss: 1.0306 - recon_style_accuracy: 0.4993 - recon_style_loss: 1.2142 - recon_subcategory_accuracy: 0.7887 - recon_subcategory_loss: 0.5918 - val_loss: 9.7576 - val_recon_category_accuracy: 0.9969 - val_recon_category_loss: 0.0136 - val_recon_color_accuracy: 0.7004 - val_recon_color_loss: 0.9333 - val_recon_material_accuracy: 0.8809 - val_recon_material_loss: 0.3581 - val_recon_numerical_loss: 0.8260 - val_recon_season_accuracy: 0.5769 - val_recon_season_loss: 1.0427 - val_recon_size_accuracy: 0.7243 - val_recon_size_loss: 0.7329 - val_recon_style_accuracy: 0.6440 - val_recon_style_loss: 0.9344 - val_recon_subcategory_accuracy: 0.9745 - val_recon_subcategory_loss: 0.1666 - learning_rate: 0.0010
Epoch 4/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 12.8130 - recon_category_accuracy: 0.9469 - recon_category_loss: 0.1547 - recon_color_accuracy: 0.6453 - recon_color_loss: 1.0259 - recon_material_accuracy: 0.7615 - recon_material_loss: 0.6269 - recon_numerical_loss: 0.9221 - recon_season_accuracy: 0.5484 - recon_season_loss: 1.0719 - recon_size_accuracy: 0.6348 - recon_size_loss: 0.9114 - recon_style_accuracy: 0.5718 - recon_style_loss: 1.0407 - recon_subcategory_accuracy: 0.8415 - recon_subcategory_loss: 0.4642 - val_loss: 6.8710 - val_recon_category_accuracy: 0.9968 - val_recon_category_loss: 0.0108 - val_recon_color_accuracy: 0.8460 - val_recon_color_loss: 0.5206 - val_recon_material_accuracy: 0.9001 - val_recon_material_loss: 0.2944 - val_recon_numerical_loss: 0.8903 - val_recon_season_accuracy: 0.7031 - val_recon_season_loss: 0.7781 - val_recon_size_accuracy: 0.7973 - val_recon_size_loss: 0.5696 - val_recon_style_accuracy: 0.7471 - val_recon_style_loss: 0.6957 - val_recon_subcategory_accuracy: 0.9931 - val_recon_subcategory_loss: 0.0715 - learning_rate: 0.0010
Epoch 5/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 11.2449 - recon_category_accuracy: 0.9458 - recon_category_loss: 0.1863 - recon_color_accuracy: 0.6957 - recon_color_loss: 0.8534 - recon_material_accuracy: 0.7789 - recon_material_loss: 0.5934 - recon_numerical_loss: 0.9152 - recon_season_accuracy: 0.6146 - recon_season_loss: 0.9178 - recon_size_accuracy: 0.6676 - recon_size_loss: 0.8296 - recon_style_accuracy: 0.6404 - recon_style_loss: 0.8829 - recon_subcategory_accuracy: 0.8633 - recon_subcategory_loss: 0.4108 - val_loss: 5.5409 - val_recon_category_accuracy: 0.9944 - val_recon_category_loss: 0.0171 - val_recon_color_accuracy: 0.8839 - val_recon_color_loss: 0.3798 - val_recon_material_accuracy: 0.8832 - val_recon_material_loss: 0.2994 - val_recon_numerical_loss: 0.8981 - val_recon_season_accuracy: 0.8257 - val_recon_season_loss: 0.5824 - val_recon_size_accuracy: 0.8276 - val_recon_size_loss: 0.5047 - val_recon_style_accuracy: 0.8568 - val_recon_style_loss: 0.5042 - val_recon_subcategory_accuracy: 0.9968 - val_recon_subcategory_loss: 0.0458 - learning_rate: 0.0010
Epoch 6/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 10.6459 - recon_category_accuracy: 0.9424 - recon_category_loss: 0.1794 - recon_color_accuracy: 0.7100 - recon_color_loss: 0.8161 - recon_material_accuracy: 0.7889 - recon_material_loss: 0.5602 - recon_numerical_loss: 0.9024 - recon_season_accuracy: 0.6686 - recon_season_loss: 0.8011 - recon_size_accuracy: 0.6881 - recon_size_loss: 0.7763 - recon_style_accuracy: 0.6723 - recon_style_loss: 0.8117 - recon_subcategory_accuracy: 0.8650 - recon_subcategory_loss: 0.4126 - val_loss: 4.4957 - val_recon_category_accuracy: 0.9973 - val_recon_category_loss: 0.0082 - val_recon_color_accuracy: 0.9211 - val_recon_color_loss: 0.3117 - val_recon_material_accuracy: 0.9513 - val_recon_material_loss: 0.2003 - val_recon_numerical_loss: 0.8334 - val_recon_season_accuracy: 0.8364 - val_recon_season_loss: 0.4871 - val_recon_size_accuracy: 0.8483 - val_recon_size_loss: 0.4111 - val_recon_style_accuracy: 0.8827 - val_recon_style_loss: 0.4283 - val_recon_subcategory_accuracy: 0.9972 - val_recon_subcategory_loss: 0.0327 - learning_rate: 0.0010
Epoch 7/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.7138 - recon_category_accuracy: 0.9453 - recon_category_loss: 0.1582 - recon_color_accuracy: 0.7331 - recon_color_loss: 0.7508 - recon_material_accuracy: 0.8124 - recon_material_loss: 0.4903 - recon_numerical_loss: 0.8905 - recon_season_accuracy: 0.7002 - recon_season_loss: 0.7266 - recon_size_accuracy: 0.7181 - recon_size_loss: 0.7057 - recon_style_accuracy: 0.7016 - recon_style_loss: 0.7356 - recon_subcategory_accuracy: 0.8770 - recon_subcategory_loss: 0.3536 - val_loss: 3.7826 - val_recon_category_accuracy: 0.9977 - val_recon_category_loss: 0.0064 - val_recon_color_accuracy: 0.9228 - val_recon_color_loss: 0.2773 - val_recon_material_accuracy: 0.9569 - val_recon_material_loss: 0.1627 - val_recon_numerical_loss: 0.8877 - val_recon_season_accuracy: 0.9421 - val_recon_season_loss: 0.3470 - val_recon_size_accuracy: 0.8711 - val_recon_size_loss: 0.3662 - val_recon_style_accuracy: 0.9371 - val_recon_style_loss: 0.3392 - val_recon_subcategory_accuracy: 0.9995 - val_recon_subcategory_loss: 0.0262 - learning_rate: 0.0010
Epoch 8/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.9985 - recon_category_accuracy: 0.9499 - recon_category_loss: 0.1455 - recon_color_accuracy: 0.7417 - recon_color_loss: 0.7282 - recon_material_accuracy: 0.8318 - recon_material_loss: 0.4482 - recon_numerical_loss: 0.8952 - recon_season_accuracy: 0.7370 - recon_season_loss: 0.6411 - recon_size_accuracy: 0.7438 - recon_size_loss: 0.6623 - recon_style_accuracy: 0.7262 - recon_style_loss: 0.6795 - recon_subcategory_accuracy: 0.8859 - recon_subcategory_loss: 0.3290 - val_loss: 3.2468 - val_recon_category_accuracy: 0.9996 - val_recon_category_loss: 0.0039 - val_recon_color_accuracy: 0.9412 - val_recon_color_loss: 0.2498 - val_recon_material_accuracy: 0.9716 - val_recon_material_loss: 0.1368 - val_recon_numerical_loss: 0.8241 - val_recon_season_accuracy: 0.9619 - val_recon_season_loss: 0.2808 - val_recon_size_accuracy: 0.9212 - val_recon_size_loss: 0.3039 - val_recon_style_accuracy: 0.9301 - val_recon_style_loss: 0.3008 - val_recon_subcategory_accuracy: 1.0000 - val_recon_subcategory_loss: 0.0165 - learning_rate: 0.0010
Epoch 9/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5445 - recon_category_accuracy: 0.9491 - recon_category_loss: 0.1514 - recon_color_accuracy: 0.7487 - recon_color_loss: 0.7080 - recon_material_accuracy: 0.8448 - recon_material_loss: 0.4193 - recon_numerical_loss: 0.8849 - recon_season_accuracy: 0.7600 - recon_season_loss: 0.6010 - recon_size_accuracy: 0.7581 - recon_size_loss: 0.6118 - recon_style_accuracy: 0.7487 - recon_style_loss: 0.6453 - recon_subcategory_accuracy: 0.8906 - recon_subcategory_loss: 0.3218 - val_loss: 2.8767 - val_recon_category_accuracy: 0.9991 - val_recon_category_loss: 0.0051 - val_recon_color_accuracy: 0.9411 - val_recon_color_loss: 0.2479 - val_recon_material_accuracy: 0.9704 - val_recon_material_loss: 0.1149 - val_recon_numerical_loss: 0.8524 - val_recon_season_accuracy: 0.9795 - val_recon_season_loss: 0.2452 - val_recon_size_accuracy: 0.9581 - val_recon_size_loss: 0.2307 - val_recon_style_accuracy: 0.9717 - val_recon_style_loss: 0.2492 - val_recon_subcategory_accuracy: 0.9999 - val_recon_subcategory_loss: 0.0133 - learning_rate: 0.0010
Epoch 10/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.2910 - recon_category_accuracy: 0.9490 - recon_category_loss: 0.1757 - recon_color_accuracy: 0.7565 - recon_color_loss: 0.6694 - recon_material_accuracy: 0.8538 - recon_material_loss: 0.3977 - recon_numerical_loss: 0.8810 - recon_season_accuracy: 0.7674 - recon_season_loss: 0.5731 - recon_size_accuracy: 0.7760 - recon_size_loss: 0.5749 - recon_style_accuracy: 0.7551 - recon_style_loss: 0.6101 - recon_subcategory_accuracy: 0.8911 - recon_subcategory_loss: 0.3514 - val_loss: 2.5614 - val_recon_category_accuracy: 0.9992 - val_recon_category_loss: 0.0050 - val_recon_color_accuracy: 0.9491 - val_recon_color_loss: 0.2199 - val_recon_material_accuracy: 0.9852 - val_recon_material_loss: 0.0906 - val_recon_numerical_loss: 0.8195 - val_recon_season_accuracy: 0.9787 - val_recon_season_loss: 0.2062 - val_recon_size_accuracy: 0.9531 - val_recon_size_loss: 0.2072 - val_recon_style_accuracy: 0.9623 - val_recon_style_loss: 0.2248 - val_recon_subcategory_accuracy: 0.9999 - val_recon_subcategory_loss: 0.0136 - learning_rate: 0.0010
Epoch 11/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.2524 - recon_category_accuracy: 0.9456 - recon_category_loss: 0.1726 - recon_color_accuracy: 0.7572 - recon_color_loss: 0.6598 - recon_material_accuracy: 0.8634 - recon_material_loss: 0.3758 - recon_numerical_loss: 0.8691 - recon_season_accuracy: 0.7787 - recon_season_loss: 0.5516 - recon_size_accuracy: 0.7761 - recon_size_loss: 0.5691 - recon_style_accuracy: 0.7602 - recon_style_loss: 0.6092 - recon_subcategory_accuracy: 0.8844 - recon_subcategory_loss: 0.3530 - val_loss: 2.3202 - val_recon_category_accuracy: 1.0000 - val_recon_category_loss: 0.0028 - val_recon_color_accuracy: 0.9651 - val_recon_color_loss: 0.1972 - val_recon_material_accuracy: 0.9901 - val_recon_material_loss: 0.0745 - val_recon_numerical_loss: 0.8108 - val_recon_season_accuracy: 0.9929 - val_recon_season_loss: 0.1755 - val_recon_size_accuracy: 0.9568 - val_recon_size_loss: 0.1892 - val_recon_style_accuracy: 0.9669 - val_recon_style_loss: 0.2094 - val_recon_subcategory_accuracy: 1.0000 - val_recon_subcategory_loss: 0.0104 - learning_rate: 0.0010
Epoch 12/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.7944 - recon_category_accuracy: 0.9503 - recon_category_loss: 0.1438 - recon_color_accuracy: 0.7682 - recon_color_loss: 0.6631 - recon_material_accuracy: 0.8687 - recon_material_loss: 0.3551 - recon_numerical_loss: 0.8699 - recon_season_accuracy: 0.7862 - recon_season_loss: 0.5379 - recon_size_accuracy: 0.7952 - recon_size_loss: 0.5291 - recon_style_accuracy: 0.7727 - recon_style_loss: 0.5708 - recon_subcategory_accuracy: 0.8975 - recon_subcategory_loss: 0.2969 - val_loss: 2.2377 - val_recon_category_accuracy: 1.0000 - val_recon_category_loss: 0.0016 - val_recon_color_accuracy: 0.9439 - val_recon_color_loss: 0.2213 - val_recon_material_accuracy: 0.9929 - val_recon_material_loss: 0.0637 - val_recon_numerical_loss: 0.8655 - val_recon_season_accuracy: 0.9797 - val_recon_season_loss: 0.1739 - val_recon_size_accuracy: 0.9741 - val_recon_size_loss: 0.1557 - val_recon_style_accuracy: 0.9919 - val_recon_style_loss: 0.1818 - val_recon_subcategory_accuracy: 1.0000 - val_recon_subcategory_loss: 0.0078 - learning_rate: 0.0010
Epoch 13/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.3614 - recon_category_accuracy: 0.9549 - recon_category_loss: 0.1486 - recon_color_accuracy: 0.7730 - recon_color_loss: 0.6356 - recon_material_accuracy: 0.8776 - recon_material_loss: 0.3314 - recon_numerical_loss: 0.8784 - recon_season_accuracy: 0.8028 - recon_season_loss: 0.4918 - recon_size_accuracy: 0.8079 - recon_size_loss: 0.4968 - recon_style_accuracy: 0.7936 - recon_style_loss: 0.5361 - recon_subcategory_accuracy: 0.9047 - recon_subcategory_loss: 0.2959 - val_loss: 2.0049 - val_recon_category_accuracy: 1.0000 - val_recon_category_loss: 0.0022 - val_recon_color_accuracy: 0.9535 - val_recon_color_loss: 0.1929 - val_recon_material_accuracy: 0.9952 - val_recon_material_loss: 0.0536 - val_recon_numerical_loss: 0.8575 - val_recon_season_accuracy: 0.9921 - val_recon_season_loss: 0.1363 - val_recon_size_accuracy: 0.9791 - val_recon_size_loss: 0.1423 - val_recon_style_accuracy: 0.9903 - val_recon_style_loss: 0.1603 - val_recon_subcategory_accuracy: 1.0000 - val_recon_subcategory_loss: 0.0090 - learning_rate: 0.0010
Epoch 14/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.3471 - recon_category_accuracy: 0.9509 - recon_category_loss: 0.1588 - recon_color_accuracy: 0.7860 - recon_color_loss: 0.5911 - recon_material_accuracy: 0.8737 - recon_material_loss: 0.3517 - recon_numerical_loss: 0.8739 - recon_season_accuracy: 0.8040 - recon_season_loss: 0.5005 - recon_size_accuracy: 0.8070 - recon_size_loss: 0.5016 - recon_style_accuracy: 0.7960 - recon_style_loss: 0.5299 - recon_subcategory_accuracy: 0.9023 - recon_subcategory_loss: 0.3077 - val_loss: 1.9401 - val_recon_category_accuracy: 1.0000 - val_recon_category_loss: 0.0014 - val_recon_color_accuracy: 0.9635 - val_recon_color_loss: 0.1862 - val_recon_material_accuracy: 0.9920 - val_recon_material_loss: 0.0625 - val_recon_numerical_loss: 0.8698 - val_recon_season_accuracy: 0.9960 - val_recon_season_loss: 0.1249 - val_recon_size_accuracy: 0.9775 - val_recon_size_loss: 0.1332 - val_recon_style_accuracy: 0.9852 - val_recon_style_loss: 0.1500 - val_recon_subcategory_accuracy: 0.9999 - val_recon_subcategory_loss: 0.0060 - learning_rate: 0.0010
Epoch 15/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.1827 - recon_category_accuracy: 0.9539 - recon_category_loss: 0.1407 - recon_color_accuracy: 0.7860 - recon_color_loss: 0.5974 - recon_material_accuracy: 0.8792 - recon_material_loss: 0.3332 - recon_numerical_loss: 0.8679 - recon_season_accuracy: 0.8079 - recon_season_loss: 0.4875 - recon_size_accuracy: 0.8166 - recon_size_loss: 0.4736 - recon_style_accuracy: 0.8040 - recon_style_loss: 0.5116 - recon_subcategory_accuracy: 0.9044 - recon_subcategory_loss: 0.2836 - val_loss: 1.7913 - val_recon_category_accuracy: 1.0000 - val_recon_category_loss: 0.0018 - val_recon_color_accuracy: 0.9699 - val_recon_color_loss: 0.1661 - val_recon_material_accuracy: 0.9959 - val_recon_material_loss: 0.0437 - val_recon_numerical_loss: 0.8223 - val_recon_season_accuracy: 0.9805 - val_recon_season_loss: 0.1414 - val_recon_size_accuracy: 0.9951 - val_recon_size_loss: 0.1252 - val_recon_style_accuracy: 0.9937 - val_recon_style_loss: 0.1311 - val_recon_subcategory_accuracy: 1.0000 - val_recon_subcategory_loss: 0.0055 - learning_rate: 0.0010
Epoch 16/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 6.8288 - recon_category_accuracy: 0.9563 - recon_category_loss: 0.1275 - recon_color_accuracy: 0.7956 - recon_color_loss: 0.5641 - recon_material_accuracy: 0.8858 - recon_material_loss: 0.3211 - recon_numerical_loss: 0.8620 - recon_season_accuracy: 0.8174 - recon_season_loss: 0.4667 - recon_size_accuracy: 0.8161 - recon_size_loss: 0.4788 - recon_style_accuracy: 0.8155 - recon_style_loss: 0.4707 - recon_subcategory_accuracy: 0.9106 - recon_subcategory_loss: 0.2594 - val_loss: 1.6113 - val_recon_category_accuracy: 1.0000 - val_recon_category_loss: 8.7881e-04 - val_recon_color_accuracy: 0.9719 - val_recon_color_loss: 0.1488 - val_recon_material_accuracy: 0.9899 - val_recon_material_loss: 0.0546 - val_recon_numerical_loss: 0.8364 - val_recon_season_accuracy: 0.9992 - val_recon_season_loss: 0.0994 - val_recon_size_accuracy: 0.9849 - val_recon_size_loss: 0.1020 - val_recon_style_accuracy: 0.9964 - val_recon_style_loss: 0.1106 - val_recon_subcategory_accuracy: 1.0000 - val_recon_subcategory_loss: 0.0043 - learning_rate: 0.0010
Epoch 17/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 6.5558 - recon_category_accuracy: 0.9575 - recon_category_loss: 0.1313 - recon_color_accuracy: 0.8068 - recon_color_loss: 0.5387 - recon_material_accuracy: 0.8879 - recon_material_loss: 0.3285 - recon_numerical_loss: 0.8660 - recon_season_accuracy: 0.8278 - recon_season_loss: 0.4448 - recon_size_accuracy: 0.8243 - recon_size_loss: 0.4549 - recon_style_accuracy: 0.8249 - recon_style_loss: 0.4550 - recon_subcategory_accuracy: 0.9161 - recon_subcategory_loss: 0.2621 - val_loss: 1.5378 - val_recon_category_accuracy: 1.0000 - val_recon_category_loss: 0.0012 - val_recon_color_accuracy: 0.9736 - val_recon_color_loss: 0.1399 - val_recon_material_accuracy: 0.9979 - val_recon_material_loss: 0.0394 - val_recon_numerical_loss: 0.8387 - val_recon_season_accuracy: 0.9900 - val_recon_season_loss: 0.1141 - val_recon_size_accuracy: 0.9860 - val_recon_size_loss: 0.1005 - val_recon_style_accuracy: 0.9968 - val_recon_style_loss: 0.0931 - val_recon_subcategory_accuracy: 1.0000 - val_recon_subcategory_loss: 0.0042 - learning_rate: 0.0010
Epoch 18/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 6.6573 - recon_category_accuracy: 0.9541 - recon_category_loss: 0.1380 - recon_color_accuracy: 0.8053 - recon_color_loss: 0.5529 - recon_material_accuracy: 0.8910 - recon_material_loss: 0.3139 - recon_numerical_loss: 0.8717 - recon_season_accuracy: 0.8168 - recon_season_loss: 0.4671 - recon_size_accuracy: 0.8330 - recon_size_loss: 0.4310 - recon_style_accuracy: 0.8272 - recon_style_loss: 0.4505 - recon_subcategory_accuracy: 0.9121 - recon_subcategory_loss: 0.2908 - val_loss: 1.4853 - val_recon_category_accuracy: 1.0000 - val_recon_category_loss: 9.4668e-04 - val_recon_color_accuracy: 0.9796 - val_recon_color_loss: 0.1251 - val_recon_material_accuracy: 0.9980 - val_recon_material_loss: 0.0314 - val_recon_numerical_loss: 0.8506 - val_recon_season_accuracy: 0.9932 - val_recon_season_loss: 0.1123 - val_recon_size_accuracy: 0.9993 - val_recon_size_loss: 0.0867 - val_recon_style_accuracy: 0.9955 - val_recon_style_loss: 0.1060 - val_recon_subcategory_accuracy: 1.0000 - val_recon_subcategory_loss: 0.0047 - learning_rate: 0.0010
Epoch 19/100

In [66]:
print(history_ae.history["val_recon_numerical_loss"][-1])
print(history_ae.history["recon_numerical_loss"][-1])

0.8063198924064636
0.8448784351348877

In [67]:
loss_weights["recon_numerical"] = 5.0  # au lieu de 0.5

In [68]:
autoencoder.compile(
    optimizer=tf.keras.optimizers.Adam(1e-3),
    loss=losses,
    loss_weights=loss_weights,
    metrics=metrics
)

history_ae = autoencoder.fit(
    train_inputs, train_targets,
    validation_data=(val_inputs, val_targets),
    epochs=100, batch_size=256,
    callbacks=[early_stop, reduce_lr], verbose=1
)

print("\n--- Accuracy de reconstruction par variable (val) ---")
for col in cat_features:
    acc_key = f"val_recon_{col}_accuracy"
    if acc_key in history_ae.history:
        print(f"{col}: {history_ae.history[acc_key][-1]:.3f}")

print("val_recon_numerical_loss:", history_ae.history["val_recon_numerical_loss"][-1])

product_embeddings_ae = embedding_model.predict(all_inputs, batch_size=512)
check_embedding_health(product_embeddings_ae, "Autoencoder v3")
print("--- Autoencoder v3 ---")
evaluate_model(lambda pid, k: recommend_autoencoder(pid, k))

Epoch 1/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 22s 62ms/step - loss: 7.7257 - recon_category_accuracy: 0.9733 - recon_category_loss: 0.0788 - recon_color_accuracy: 0.9092 - recon_color_loss: 0.2844 - recon_material_accuracy: 0.9329 - recon_material_loss: 0.1773 - recon_numerical_loss: 0.8149 - recon_season_accuracy: 0.8990 - recon_season_loss: 0.2842 - recon_size_accuracy: 0.8969 - recon_size_loss: 0.3001 - recon_style_accuracy: 0.9040 - recon_style_loss: 0.2581 - recon_subcategory_accuracy: 0.9455 - recon_subcategory_loss: 0.1595 - val_loss: 4.0605 - val_recon_category_accuracy: 0.9999 - val_recon_category_loss: 6.0918e-04 - val_recon_color_accuracy: 1.0000 - val_recon_color_loss: 0.0124 - val_recon_material_accuracy: 1.0000 - val_recon_material_loss: 0.0059 - val_recon_numerical_loss: 0.7372 - val_recon_season_accuracy: 1.0000 - val_recon_season_loss: 0.0276 - val_recon_size_accuracy: 0.9965 - val_recon_size_loss: 0.0893 - val_recon_style_accuracy: 1.0000 - val_recon_style_loss: 0.0161 - val_recon_subcategory_accuracy: 1.0000 - val_recon_subcategory_loss: 0.0015 - learning_rate: 0.0010
Epoch 2/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.6317 - recon_category_accuracy: 0.9714 - recon_category_loss: 0.0838 - recon_color_accuracy: 0.9051 - recon_color_loss: 0.2945 - recon_material_accuracy: 0.9302 - recon_material_loss: 0.1916 - recon_numerical_loss: 0.7711 - recon_season_accuracy: 0.8931 - recon_season_loss: 0.2964 - recon_size_accuracy: 0.8920 - recon_size_loss: 0.3000 - recon_style_accuracy: 0.9012 - recon_style_loss: 0.2624 - recon_subcategory_accuracy: 0.9436 - recon_subcategory_loss: 0.1635 - val_loss: 3.8464 - val_recon_category_accuracy: 1.0000 - val_recon_category_loss: 4.4261e-04 - val_recon_color_accuracy: 1.0000 - val_recon_color_loss: 0.0134 - val_recon_material_accuracy: 0.9985 - val_recon_material_loss: 0.0153 - val_recon_numerical_loss: 0.6927 - val_recon_season_accuracy: 1.0000 - val_recon_season_loss: 0.0542 - val_recon_size_accuracy: 0.9999 - val_recon_size_loss: 0.0509 - val_recon_style_accuracy: 1.0000 - val_recon_style_loss: 0.0165 - val_recon_subcategory_accuracy: 1.0000 - val_recon_subcategory_loss: 0.0026 - learning_rate: 0.0010
Epoch 3/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.6450 - recon_category_accuracy: 0.9690 - recon_category_loss: 0.0957 - recon_color_accuracy: 0.8983 - recon_color_loss: 0.3030 - recon_material_accuracy: 0.9210 - recon_material_loss: 0.2127 - recon_numerical_loss: 0.7305 - recon_season_accuracy: 0.8908 - recon_season_loss: 0.3166 - recon_size_accuracy: 0.8939 - recon_size_loss: 0.3085 - recon_style_accuracy: 0.8973 - recon_style_loss: 0.2749 - recon_subcategory_accuracy: 0.9374 - recon_subcategory_loss: 0.2126 - val_loss: 3.5622 - val_recon_category_accuracy: 0.9997 - val_recon_category_loss: 0.0016 - val_recon_color_accuracy: 0.9991 - val_recon_color_loss: 0.0233 - val_recon_material_accuracy: 0.9985 - val_recon_material_loss: 0.0152 - val_recon_numerical_loss: 0.6362 - val_recon_season_accuracy: 0.9996 - val_recon_season_loss: 0.0388 - val_recon_size_accuracy: 0.9995 - val_recon_size_loss: 0.0463 - val_recon_style_accuracy: 1.0000 - val_recon_style_loss: 0.0216 - val_recon_subcategory_accuracy: 1.0000 - val_recon_subcategory_loss: 0.0015 - learning_rate: 0.0010
Epoch 4/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.3152 - recon_category_accuracy: 0.9689 - recon_category_loss: 0.1001 - recon_color_accuracy: 0.9084 - recon_color_loss: 0.2752 - recon_material_accuracy: 0.9231 - recon_material_loss: 0.2067 - recon_numerical_loss: 0.6922 - recon_season_accuracy: 0.8924 - recon_season_loss: 0.3068 - recon_size_accuracy: 0.8980 - recon_size_loss: 0.2876 - recon_style_accuracy: 0.9028 - recon_style_loss: 0.2759 - recon_subcategory_accuracy: 0.9423 - recon_subcategory_loss: 0.1810 - val_loss: 3.2563 - val_recon_category_accuracy: 1.0000 - val_recon_category_loss: 3.9648e-04 - val_recon_color_accuracy: 0.9999 - val_recon_color_loss: 0.0159 - val_recon_material_accuracy: 0.9996 - val_recon_material_loss: 0.0126 - val_recon_numerical_loss: 0.5810 - val_recon_season_accuracy: 1.0000 - val_recon_season_loss: 0.0442 - val_recon_size_accuracy: 1.0000 - val_recon_size_loss: 0.0452 - val_recon_style_accuracy: 1.0000 - val_recon_style_loss: 0.0166 - val_recon_subcategory_accuracy: 1.0000 - val_recon_subcategory_loss: 0.0015 - learning_rate: 5.0000e-04
Epoch 5/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.1075 - recon_category_accuracy: 0.9702 - recon_category_loss: 0.0888 - recon_color_accuracy: 0.9078 - recon_color_loss: 0.2619 - recon_material_accuracy: 0.9223 - recon_material_loss: 0.2086 - recon_numerical_loss: 0.6684 - recon_season_accuracy: 0.8991 - recon_season_loss: 0.2872 - recon_size_accuracy: 0.8986 - recon_size_loss: 0.2821 - recon_style_accuracy: 0.9017 - recon_style_loss: 0.2679 - recon_subcategory_accuracy: 0.9439 - recon_subcategory_loss: 0.1645 - val_loss: 3.2339 - val_recon_category_accuracy: 1.0000 - val_recon_category_loss: 4.5845e-04 - val_recon_color_accuracy: 0.9997 - val_recon_color_loss: 0.0164 - val_recon_material_accuracy: 0.9995 - val_recon_material_loss: 0.0124 - val_recon_numerical_loss: 0.5776 - val_recon_season_accuracy: 1.0000 - val_recon_season_loss: 0.0471 - val_recon_size_accuracy: 1.0000 - val_recon_size_loss: 0.0388 - val_recon_style_accuracy: 1.0000 - val_recon_style_loss: 0.0183 - val_recon_subcategory_accuracy: 1.0000 - val_recon_subcategory_loss: 0.0011 - learning_rate: 5.0000e-04
Epoch 6/100
167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 6.9713 - recon_category_accuracy: 0.9732 - recon_category_loss: 0.0799 - recon_color_accuracy: 0.9094 - recon_color_loss: 0.2622 - recon_material_accuracy: 0.9241 - recon_material_loss: 0.2076 - recon_numerical_loss: 0.6593 - recon_season_accuracy: 0.8981 - recon_season_loss: 0.2964 - recon_size_accuracy: 0.9036 - recon_size_loss: 0.2690 - recon_style_accuracy: 0.9035 - recon_style_loss: 0.2669 - recon_subcategory_accuracy: 0.9456 - recon_subcategory_loss: 0.1555 - val_loss: 3.0533 - val_recon_category_accuracy: 1.0000 - val_recon_category_loss: 4.1057e-04 - val_recon_color_accuracy: 0.9997 - val_recon_color_loss: 0.0147 - val_recon_material_accuracy: 0.9989 - val_recon_material_loss: 0.0152 - val_recon_numerical_loss: 0.5464 - val_recon_season_accuracy: 1.0000 - val_recon_season_loss: 0.0347 - val_recon_size_accuracy: 1.0000 - val_recon_size_loss: 0.0341 - val_recon_style_accuracy: 1.0000 - val_recon_style_loss: 0.0190 - val_recon_subcategory_accuracy: 1.0000 - val_recon_subcategory_loss: 0.0016 - learning_rate: 5.0000e-04

--- Accuracy de reconstruction par variable (val) ---
category: 1.000
subcategory: 1.000
material: 0.999
color: 1.000
season: 1.000
style: 1.000
size: 1.000
val_recon_numerical_loss: 0.5463953018188477
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[Autoencoder v3] std par dimension (moyenne): 2.6042
[Autoencoder v3] similarité cosine moyenne (paires aléatoires): 0.0077
[Autoencoder v3] similarité cosine std: 0.2666
--- Autoencoder v3 ---
Category match@5: 0.997
Subcategory match@5: 0.993
Écart prix relatif moyen: 0.396